---
- hosts: localhost
  become: yes
  gather_facts: no  

  tasks:
    - name: add several users
      user:
        name: "{{ item }}"
        state: present
        groups: "sudo"
      with_items:
        - testuser1
        - testuser2


