---
- hosts: localhost
  become: yes
  gather_facts: no  
  vars:
    packages: [vim,make,curl]

  tasks:

   - name: add several users
     user: name={{ item.name }} state=present groups={{ item.groups }}
     with_items:
      - { name: 'testuser1', groups: 'wheel' }
      - { name: 'testuser2', groups: 'root' }

